language: generic
addons:
  apt:
    packages:
      - libcurl4-openssl-dev

services:
  - docker

before_install:
- docker pull etopeter/kubectl-utilization-test

script:
- make test

after_success: |
  bash <(curl -s https://codecov.io/bash)
