language: bash
addons:
  apt:
    packages:
      - libcurl4-openssl-dev

services:
  - docker

before_install:
- docker pull etopeter/kubectl-utilization-test
- mkdir coverage && sudo chown 1000 coverage

script:
- make test
- bash <(curl -s https://codecov.io/bash)
